# version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: starwars
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
